# Generated by Django 6.1.1 on 2026-09-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_session',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('strt_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Dor', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
